import { StyleSheet } from '../../lib/web-ui';
import { colors } from '../shared/ui/theme';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: colors.canvasDeep,
  },
  authSafeArea: {
    backgroundColor: '#2D1811',
  },
  keyboardView: {
    flex: 1,
  },
  shell: {
    alignSelf: 'center',
    flex: 1,
    backgroundColor: colors.background,
    maxWidth: 760,
    minWidth: 0,
    overflow: 'hidden',
    paddingHorizontal: 12,
    paddingTop: 8,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.09,
    shadowRadius: 28,
    width: '100%',
  },
  header: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 252, 247, 0.94)',
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
    minHeight: 64,
    paddingHorizontal: 10,
    paddingVertical: 8,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.1,
    shadowRadius: 20,
    elevation: 3,
  },
  brandLockup: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 10,
    minWidth: 0,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.lineStrong,
    borderRadius: 13,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    overflow: 'hidden',
    padding: 3,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.12,
    shadowRadius: 14,
    width: 46,
  },
  brandLogo: {
    borderRadius: 10,
    height: '100%',
    resizeMode: 'cover',
    width: '100%',
  },
  brandCopy: {
    flex: 1,
    minWidth: 0,
  },
  brandScript: {
    color: colors.accent,
    fontSize: 11,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 13,
  },
  appName: {
    color: colors.gold,
    fontSize: 21,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 23,
    textShadowColor: colors.primary,
    textShadowOffset: { width: 1, height: 1 },
    textShadowRadius: 0,
  },
  appSubtitle: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 3,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.lineStrong,
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 12,
    width: 44,
  },
  headerActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexShrink: 0,
    gap: 7,
  },
  accountAvatarButton: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderColor: colors.primary,
    borderRadius: 999,
    borderWidth: 2,
    height: 46,
    justifyContent: 'center',
    padding: 2,
    width: 46,
  },
  profileAvatar: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    height: 38,
    overflow: 'hidden',
    width: 38,
  },
  profileAvatarLarge: {
    borderColor: 'rgba(255, 248, 238, 0.52)',
    borderWidth: 3,
    height: 92,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.24,
    shadowRadius: 18,
    width: 92,
  },
  profileAvatarImage: {
    height: '100%',
    resizeMode: 'cover',
    width: '100%',
  },
  accountPresenceDot: {
    backgroundColor: '#78A85B',
    borderColor: colors.surfaceStrong,
    borderRadius: 999,
    borderWidth: 2,
    bottom: -1,
    height: 12,
    position: 'absolute',
    right: -1,
    width: 12,
  },
  accountPresenceDotSyncing: {
    backgroundColor: colors.gold,
  },
  accountPresenceDotError: {
    backgroundColor: colors.rose,
  },
  pressed: {
    opacity: 0.72,
  },
  centerScreen: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loadingLogo: {
    borderRadius: 8,
    height: 72,
    marginBottom: 14,
    width: 72,
  },
  loadingTitle: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
  },
  loadingText: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 8,
    textAlign: 'center',
  },
  authContent: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingBottom: 28,
  },
  authScrollContent: {
    flexGrow: 1,
    backgroundColor: '#2D1811',
    backgroundImage:
      'radial-gradient(circle at 12% 8%, rgba(231, 182, 64, 0.12), transparent 34%), linear-gradient(145deg, #3A2118 0%, #24130E 100%)',
    minHeight: '100%',
  },
  authScrollContentCard: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
  },
  authScrollContentWide: {
    paddingHorizontal: 28,
    paddingVertical: 30,
  },
  authViewport: {
    flexGrow: 1,
    backgroundColor: '#FFFBF6',
    width: '100%',
  },
  authViewportCard: {
    alignSelf: 'center',
    borderRadius: 30,
    flexGrow: 0,
    maxWidth: 520,
    minHeight: 620,
    overflow: 'hidden',
    shadowColor: '#160A06',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.28,
    shadowRadius: 40,
    width: '100%',
  },
  authViewportWide: {
    alignSelf: 'center',
    borderRadius: 32,
    flexDirection: 'row',
    flexGrow: 0,
    maxWidth: 1080,
    minHeight: 650,
    overflow: 'hidden',
    shadowColor: '#160A06',
    shadowOffset: { width: 0, height: 24 },
    shadowOpacity: 0.3,
    shadowRadius: 48,
    width: '100%',
  },
  authHero: {
    alignItems: 'center',
    backgroundColor: '#3B2118',
    backgroundImage: 'linear-gradient(150deg, #4B2B20 0%, #2B1711 100%)',
    justifyContent: 'center',
    minHeight: 210,
    paddingBottom: 54,
    paddingHorizontal: 24,
    paddingTop: 26,
  },
  authHeroWide: {
    alignItems: 'flex-start',
    flexShrink: 0,
    justifyContent: 'space-between',
    minHeight: 650,
    paddingBottom: 44,
    paddingHorizontal: 38,
    paddingTop: 44,
    width: '43%',
  },
  authBrandLockup: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
  },
  authBrandLockupWide: {
    justifyContent: 'flex-start',
  },
  authHeroLogoFrame: {
    backgroundColor: '#FFF9F0',
    borderColor: 'rgba(255, 249, 240, 0.48)',
    borderRadius: 19,
    borderWidth: 1,
    height: 72,
    overflow: 'hidden',
    padding: 3,
    shadowColor: '#160A06',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    width: 72,
  },
  authHeroLogoFrameWide: {
    borderRadius: 21,
    height: 82,
    width: 82,
  },
  authHeroLogo: {
    borderRadius: 16,
    height: '100%',
    resizeMode: 'cover',
    width: '100%',
  },
  authBrandCopy: {
    marginLeft: 14,
  },
  authBrandName: {
    color: '#FFF9F0',
    fontSize: 22,
    fontWeight: '800',
    letterSpacing: -0.35,
    lineHeight: 27,
  },
  authBrandKicker: {
    color: '#F2C66D',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.45,
    lineHeight: 15,
    marginTop: 3,
  },
  authHeroMessage: {
    maxWidth: 350,
  },
  authHeroTitle: {
    color: '#FFF9F0',
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -1,
    lineHeight: 42,
  },
  authHeroDescription: {
    color: 'rgba(255, 249, 240, 0.7)',
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 22,
    marginTop: 14,
  },
  authHeroDescriptionMobile: {
    color: 'rgba(255, 249, 240, 0.72)',
    fontSize: 13,
    fontWeight: '600',
    lineHeight: 19,
    marginTop: 14,
    textAlign: 'center',
  },
  authHeroFeatures: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    width: '100%',
  },
  authHeroFeature: {
    alignItems: 'center',
    backgroundColor: 'rgba(255, 249, 240, 0.08)',
    borderColor: 'rgba(255, 249, 240, 0.13)',
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    minHeight: 38,
    paddingHorizontal: 12,
  },
  authHeroFeatureText: {
    color: 'rgba(255, 249, 240, 0.88)',
    fontSize: 12,
    fontWeight: '700',
  },
  authSheet: {
    backgroundColor: '#FFFBF6',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    flexGrow: 1,
    marginTop: -28,
    paddingBottom: 32,
    paddingHorizontal: 20,
    paddingTop: 28,
    shadowColor: '#1C0D08',
    shadowOffset: { width: 0, height: -10 },
    shadowOpacity: 0.08,
    shadowRadius: 24,
  },
  authSheetWide: {
    borderRadius: 0,
    boxShadow: 'none',
    justifyContent: 'center',
    marginTop: 0,
    paddingBottom: 52,
    paddingHorizontal: 54,
    paddingTop: 52,
    shadowOpacity: 0,
    width: '57%',
  },
  authForm: {
    alignSelf: 'center',
    gap: 20,
    maxWidth: 440,
    width: '100%',
  },
  authSheetHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 18,
    justifyContent: 'space-between',
  },
  authSheetCopy: {
    flex: 1,
  },
  authSheetEyebrow: {
    color: '#875334',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1.35,
    lineHeight: 15,
  },
  authSheetTitle: {
    color: colors.ink,
    fontSize: 29,
    fontWeight: '800',
    letterSpacing: -0.65,
    lineHeight: 35,
    marginTop: 3,
  },
  authSheetSubtitle: {
    color: colors.muted,
    fontSize: 14,
    fontWeight: '500',
    lineHeight: 20,
    marginTop: 6,
  },
  authSheetIcon: {
    alignItems: 'center',
    backgroundColor: '#F3E7D8',
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  authFields: {
    gap: 16,
  },
  authField: {
    gap: 8,
  },
  authFieldLabel: {
    color: '#433126',
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
  },
  authFieldLabelFocused: {
    color: colors.primary,
  },
  authFieldShell: {
    alignItems: 'center',
    backgroundColor: '#FFFDF9',
    borderColor: '#D8C9B9',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    minHeight: 56,
    paddingHorizontal: 8,
  },
  authFieldShellFocused: {
    backgroundColor: '#FFFFFF',
    borderColor: colors.primary,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.13,
    shadowRadius: 12,
  },
  authFieldIcon: {
    alignItems: 'center',
    backgroundColor: '#F5EDE3',
    borderRadius: 11,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  authFieldIconFocused: {
    backgroundColor: '#EEE0CE',
  },
  authFieldInput: {
    color: colors.ink,
    flex: 1,
    fontSize: 16,
    fontWeight: '500',
    letterSpacing: 0,
    minHeight: 52,
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  authFieldTrailing: {
    alignItems: 'center',
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  authBranchSection: {
    backgroundColor: '#F8F1E8',
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    gap: 10,
    padding: 14,
  },
  authSectionHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  authSectionTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
  },
  authPrimaryButton: {
    alignItems: 'center',
    backgroundColor: '#4D2B1E',
    borderRadius: 14,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 56,
    paddingLeft: 19,
    paddingRight: 9,
    shadowColor: '#3A1D13',
    shadowOffset: { width: 0, height: 9 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 4,
  },
  authPrimaryButtonPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.99 }],
  },
  authPrimaryButtonDisabled: {
    opacity: 0.58,
  },
  authPrimaryButtonText: {
    color: colors.onDark,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.1,
  },
  authPrimaryButtonIcon: {
    alignItems: 'center',
    backgroundColor: '#F0C55F',
    borderRadius: 11,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  authSwitchRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    minHeight: 44,
  },
  authSwitchPrompt: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '500',
  },
  authSwitchButton: {
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 7,
  },
  authSwitchButtonText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '800',
  },
  authFeedback: {
    alignItems: 'flex-start',
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    padding: 12,
  },
  authFeedbackSuccess: {
    backgroundColor: colors.blueSoft,
    borderColor: 'rgba(72, 104, 69, 0.26)',
  },
  authFeedbackError: {
    backgroundColor: colors.roseSoft,
    borderColor: 'rgba(180, 72, 60, 0.28)',
  },
  authFeedbackInfo: {
    backgroundColor: colors.amberSoft,
    borderColor: 'rgba(185, 101, 36, 0.28)',
  },
  authFeedbackTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 18,
  },
  authFeedbackMessage: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 17,
    marginTop: 2,
  },
  authFeedbackDismiss: {
    alignItems: 'center',
    height: 26,
    justifyContent: 'center',
    marginTop: -4,
    width: 26,
  },
  authCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 14,
    padding: 16,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 14 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 4,
  },
  authLogo: {
    alignSelf: 'center',
    borderRadius: 8,
    height: 74,
    width: 74,
  },
  authTitle: {
    color: colors.ink,
    fontSize: 24,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  authHint: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 19,
    textAlign: 'center',
  },
  codeText: {
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    paddingHorizontal: 10,
    paddingVertical: 9,
    textAlign: 'center',
  },
  accountOverlay: {
    bottom: 0,
    left: 0,
    position: 'fixed',
    right: 0,
    top: 0,
    zIndex: 1000,
  },
  accountBackdrop: {
    backgroundColor: 'rgba(35, 22, 15, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  accountDrawer: {
    alignSelf: 'flex-end',
    backgroundColor: colors.background,
    borderLeftColor: colors.lineStrong,
    borderLeftWidth: 1,
    flex: 1,
    height: '100%',
    maxWidth: 430,
    minWidth: 0,
    paddingBottom: 'env(safe-area-inset-bottom)',
    paddingTop: 'env(safe-area-inset-top)',
    shadowColor: colors.deep,
    shadowOffset: { width: -16, height: 0 },
    shadowOpacity: 0.24,
    shadowRadius: 36,
    width: '100%',
    zIndex: 1,
  },
  accountDrawerHeader: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 12,
    minHeight: 72,
    paddingBottom: 10,
    paddingHorizontal: 16,
    paddingTop: 12,
  },
  accountDrawerEyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1.1,
  },
  accountDrawerTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '900',
    letterSpacing: -0.3,
    marginTop: 2,
  },
  accountCloseButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  accountDrawerContent: {
    gap: 12,
    paddingBottom: 28,
    paddingHorizontal: 12,
    paddingTop: 12,
  },
  accountHeroCard: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 22,
    overflow: 'hidden',
    paddingBottom: 18,
    paddingHorizontal: 16,
    paddingTop: 22,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 20,
  },
  accountAvatarEditor: {
    alignItems: 'center',
    marginBottom: 11,
    position: 'relative',
  },
  avatarCameraButton: {
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderColor: colors.onDark,
    borderRadius: 999,
    borderWidth: 2,
    bottom: -3,
    height: 36,
    justifyContent: 'center',
    position: 'absolute',
    right: -3,
    width: 36,
  },
  accountHeroName: {
    color: colors.onDark,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountHeroEmail: {
    color: 'rgba(255, 248, 238, 0.7)',
    fontSize: 12,
    fontWeight: '700',
    marginTop: 3,
    textAlign: 'center',
  },
  accountHeroSync: {
    color: 'rgba(255, 248, 238, 0.72)',
    fontSize: 11,
    fontWeight: '800',
    marginTop: 7,
  },
  accountHeroSyncError: {
    color: '#FFD2CA',
  },
  accountRolePill: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 5,
    marginTop: 10,
    minHeight: 30,
    paddingHorizontal: 11,
  },
  accountRolePillText: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '900',
  },
  accountSectionCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 13,
    padding: 13,
  },
  syncErrorCard: {
    alignItems: 'flex-start',
    backgroundColor: colors.roseSoft,
    borderColor: 'rgba(180, 72, 60, 0.3)',
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    padding: 12,
  },
  syncErrorTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  syncErrorText: {
    color: colors.rose,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 3,
  },
  syncRetryButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.rose,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    justifyContent: 'center',
    marginTop: 8,
    minHeight: 40,
    paddingHorizontal: 13,
  },
  syncRetryText: {
    color: colors.onDark,
    fontSize: 12,
    fontWeight: '900',
  },
  accountSectionHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 9,
  },
  accountSectionTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  accountSectionHint: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 16,
    marginTop: 2,
  },
  profileInfoRow: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 60,
    padding: 10,
  },
  profileInfoIcon: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 11,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  profileInfoCopy: {
    flex: 1,
    minWidth: 0,
  },
  profileInfoLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  profileInfoValue: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
    marginTop: 2,
  },
  accountSecurity: {
    gap: 10,
  },
  accountSecurityActions: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  accountLoadingText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    paddingVertical: 8,
    textAlign: 'center',
  },
  staffList: {
    gap: 8,
  },
  staffCard: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 15,
    borderWidth: 1,
    overflow: 'hidden',
  },
  staffCardActive: {
    borderColor: colors.primary,
  },
  staffCardButton: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
    minHeight: 70,
    padding: 10,
    textAlign: 'left',
  },
  staffCardCopy: {
    flex: 1,
    minWidth: 0,
  },
  staffCardName: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  staffCardMeta: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    marginTop: 3,
  },
  staffCardPhone: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    marginTop: 3,
  },
  staffEditor: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    gap: 12,
    padding: 11,
  },
  nativeField: {
    gap: 6,
  },
  nativeFieldHint: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    lineHeight: 15,
  },
  accountRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  accountDetails: {
    flex: 1,
    minWidth: 0,
  },
  accountActions: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  accountIcon: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  accountName: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  accountMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 2,
  },
  accountSync: {
    color: colors.primary,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: 3,
  },
  passwordToggleButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderColor: colors.primary,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 10,
  },
  passwordToggleText: {
    color: colors.onDark,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  signOutButton: {
    alignItems: 'center',
    backgroundColor: colors.rose,
    borderColor: colors.rose,
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 10,
  },
  signOutText: {
    color: colors.onDark,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  passwordPanel: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    gap: 12,
    marginTop: 2,
    paddingTop: 12,
  },
  passwordPanelHeader: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
  },
  passwordPanelTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
  },
  passwordPanelHint: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 17,
    marginTop: 3,
  },
  passwordActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'flex-end',
  },
  passwordCancelButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  passwordCancelText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  passwordSaveButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 8,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 42,
    paddingHorizontal: 16,
  },
  passwordSaveText: {
    color: colors.onDark,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  buttonDisabled: {
    opacity: 0.55,
  },
  contextPanel: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    gap: 10,
    padding: 12,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  contextLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  roleGrid: {
    gap: 8,
  },
  roleOption: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 58,
    paddingHorizontal: 10,
    paddingVertical: 9,
  },
  roleOptionActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  roleOptionTitle: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  roleOptionTitleActive: {
    color: colors.onDark,
  },
  roleOptionText: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 2,
  },
  roleOptionTextActive: {
    color: colors.onDark,
  },
  branchPills: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  branchPill: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    minHeight: 54,
    paddingHorizontal: 10,
    paddingVertical: 8,
    width: 'calc(50% - 4px)',
  },
  branchPillActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  branchPillName: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  branchPillNameActive: {
    color: colors.onDark,
  },
  branchPillMeta: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 3,
  },
  branchPillMetaActive: {
    color: colors.onDark,
  },
  tabs: {
    backgroundColor: 'rgba(255, 252, 247, 0.97)',
    borderColor: colors.line,
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 4,
    marginBottom: 8,
    marginTop: 8,
    padding: 5,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: -6 },
    shadowOpacity: 0.1,
    shadowRadius: 18,
    elevation: 4,
  },
  tab: {
    alignItems: 'center',
    borderRadius: 15,
    flex: 1,
    gap: 3,
    justifyContent: 'center',
    minHeight: 56,
    minWidth: 0,
    paddingHorizontal: 5,
  },
  tabActive: {
    backgroundColor: colors.primary,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.14,
    shadowRadius: 12,
  },
  tabText: {
    color: colors.muted,
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0,
  },
  tabTextActive: {
    color: colors.onDark,
  },
  content: {
    gap: 12,
    paddingBottom: 16,
  },
  screen: {
    gap: 14,
  },
  closingForm: {
    gap: 12,
  },
  closingSection: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
    padding: 12,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  fieldGroup: {
    gap: 8,
  },
  fieldGroupTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: 2,
  },
  plasticCupSection: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 12,
    padding: 12,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  closingSectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  closingSectionTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  cupEntry: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    gap: 8,
    padding: 10,
  },
  cupEquationRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 5,
  },
  cupName: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
    minWidth: 50,
  },
  cupEquationInput: {
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 10,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    height: 44,
    letterSpacing: 0,
    paddingHorizontal: 6,
    paddingVertical: 0,
    textAlign: 'center',
    width: 54,
  },
  inputError: {
    borderColor: colors.rose,
    backgroundColor: colors.roseSoft,
  },
  equationMark: {
    color: colors.muted,
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  soldEquationValue: {
    alignItems: 'center',
    backgroundColor: colors.accentSoft,
    borderRadius: 7,
    flexDirection: 'row',
    gap: 3,
    minHeight: 38,
    paddingHorizontal: 7,
  },
  soldEquationNumber: {
    color: colors.primary,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
  },
  equationUnit: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0,
  },
  cupBalanceRow: {
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  machineCupGroup: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 6,
  },
  machineCupLabel: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  cupBalanceBadge: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderColor: colors.lineStrong,
    borderRadius: 7,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 38,
    minWidth: 92,
    paddingHorizontal: 10,
  },
  cupBalanceBadgeShort: {
    backgroundColor: colors.roseSoft,
    borderColor: '#D79A91',
  },
  cupBalanceBadgeOver: {
    backgroundColor: colors.amberSoft,
    borderColor: '#E2B889',
  },
  cupBalanceText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  cupBalanceTextShort: {
    color: colors.rose,
  },
  cupBalanceTextOver: {
    color: colors.amber,
  },
  closingCard: {
    backgroundColor: '#F6E8D6',
    borderColor: colors.lineStrong,
    borderRadius: 14,
    borderWidth: 1,
    gap: 10,
    minHeight: 96,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  closingCardError: {
    borderColor: colors.rose,
    backgroundColor: colors.roseSoft,
  },
  requiredNotice: {
    alignItems: 'center',
    backgroundColor: colors.amberSoft,
    borderColor: '#E2B889',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  requiredNoticeText: {
    color: colors.amber,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    textAlign: 'center',
  },
  closingLabel: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  requiredMark: {
    color: colors.rose,
  },
  closingInput: {
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 12,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: 0,
    minHeight: 48,
    paddingHorizontal: 12,
    paddingVertical: 0,
  },
  closingInputError: {
    borderColor: colors.rose,
  },
  inputSuffix: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    marginTop: -6,
  },
  transferTotal: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
    marginTop: -4,
  },
  exportStage: {
    left: -5000,
    position: 'absolute',
    top: 0,
    width: 252,
  },
  exportSheet: {
    backgroundColor: colors.background,
    paddingBottom: 18,
    paddingHorizontal: 11,
    paddingTop: 14,
    width: 252,
  },
  exportPreview: {
    gap: 11,
  },
  exportCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    gap: 7,
    paddingHorizontal: 13,
    paddingVertical: 16,
  },
  exportCardTitle: {
    color: colors.ink,
    fontSize: 11.2,
    fontWeight: '800',
    letterSpacing: 0,
  },
  exportRequired: {
    color: colors.rose,
  },
  exportLines: {
    gap: 2,
  },
  exportLine: {
    color: colors.ink,
    fontSize: 8.8,
    fontWeight: '500',
    letterSpacing: 0,
    lineHeight: 17,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  sectionCopy: {
    flex: 1,
    minWidth: 0,
  },
  sectionIcon: {
    alignItems: 'center',
    backgroundColor: colors.primarySoft,
    borderRadius: 8,
    borderColor: colors.line,
    borderWidth: 1,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  sectionTitle: {
    color: colors.ink,
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: 0,
  },
  sectionSubtitle: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 1,
  },
  statusBand: {
    alignItems: 'center',
    borderColor: colors.line,
    borderWidth: 1,
    borderRadius: 16,
    flexDirection: 'row',
    gap: 12,
    padding: 14,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 1,
  },
  statusIn: {
    backgroundColor: colors.primarySoft,
  },
  statusOut: {
    backgroundColor: colors.roseSoft,
  },
  statusNeutral: {
    backgroundColor: colors.surfaceStrong,
  },
  statusIcon: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderRadius: 8,
    height: 42,
    justifyContent: 'center',
    width: 42,
  },
  statusTitle: {
    color: colors.ink,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0,
  },
  statusText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 2,
  },
  flex: {
    flex: 1,
  },
  field: {
    gap: 7,
  },
  inputLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  inputShell: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 14,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 9,
    minHeight: 48,
    paddingHorizontal: 12,
  },
  inputShellMultiline: {
    alignItems: 'flex-start',
    minHeight: 88,
    paddingTop: 11,
  },
  input: {
    color: colors.ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0,
    paddingVertical: 0,
  },
  inputTrailingButton: {
    alignItems: 'center',
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  inputMultiline: {
    minHeight: 64,
    textAlignVertical: 'top',
  },
  buttonRow: {
    flexDirection: 'row',
    gap: 10,
  },
  monthNavigator: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
    padding: 7,
  },
  monthButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    height: 44,
    justifyContent: 'center',
    width: 44,
  },
  monthCurrent: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 46,
    minWidth: 0,
    paddingHorizontal: 6,
  },
  monthCurrentPressed: {
    backgroundColor: colors.primarySoft,
    borderRadius: 12,
  },
  monthCurrentCopy: {
    minWidth: 0,
  },
  monthCurrentText: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
    textAlign: 'center',
  },
  monthCurrentHint: {
    color: colors.muted,
    fontSize: 9,
    fontWeight: '700',
    marginTop: 1,
    textAlign: 'center',
  },
  monthPickerOverlay: {
    bottom: 0,
    left: 0,
    position: 'fixed',
    right: 0,
    top: 0,
    zIndex: 1200,
  },
  monthPickerBackdrop: {
    backgroundColor: 'rgba(35, 22, 15, 0.58)',
    bottom: 0,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
    zIndex: 0,
  },
  monthPickerSheet: {
    alignSelf: 'center',
    backgroundColor: colors.background,
    borderColor: colors.lineStrong,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    bottom: 0,
    gap: 14,
    maxWidth: 430,
    paddingBottom: 'calc(18px + env(safe-area-inset-bottom))',
    paddingHorizontal: 14,
    paddingTop: 9,
    position: 'absolute',
    width: '100%',
    zIndex: 1,
  },
  monthPickerHandle: {
    alignSelf: 'center',
    backgroundColor: colors.lineStrong,
    borderRadius: 999,
    height: 4,
    width: 44,
  },
  monthPickerHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  monthPickerEyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 1,
  },
  monthPickerTitle: {
    color: colors.ink,
    fontSize: 22,
    fontWeight: '900',
    marginTop: 2,
  },
  monthPickerYearRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  monthPickerYearButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 12,
    borderWidth: 1,
    height: 46,
    justifyContent: 'center',
    width: 48,
  },
  monthPickerYearDisplay: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 13,
    flex: 1,
    justifyContent: 'center',
    minHeight: 46,
  },
  monthPickerYearText: {
    color: colors.onDark,
    fontSize: 19,
    fontWeight: '900',
  },
  monthPickerGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 7,
  },
  monthPickerOption: {
    alignItems: 'center',
    backgroundColor: colors.surfaceTint,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 54,
    paddingHorizontal: 4,
    width: 'calc(25% - 6px)',
  },
  monthPickerOptionCurrent: {
    borderColor: colors.accent,
    borderWidth: 2,
  },
  monthPickerOptionSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  monthPickerOptionText: {
    color: colors.ink,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  monthPickerOptionTextSelected: {
    color: colors.onDark,
  },
  monthPickerNowText: {
    color: colors.accent,
    fontSize: 8,
    fontWeight: '900',
    marginTop: 2,
  },
  monthPickerTodayButton: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: colors.primarySoft,
    borderColor: colors.lineStrong,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 7,
    justifyContent: 'center',
    minHeight: 44,
    paddingHorizontal: 15,
  },
  monthPickerTodayText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
  },
  attendanceQuickCard: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 11,
    padding: 12,
  },
  attendanceQuickHeading: {
    gap: 3,
  },
  attendanceQuickTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  attendanceQuickHint: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 16,
  },
  attendanceQuickFields: {
    flexDirection: 'row',
    gap: 9,
  },
  attendanceQuickField: {
    flex: 1,
    gap: 6,
  },
  attendanceQuickLabel: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '800',
  },
  attendanceQuickInput: {
    backgroundColor: '#F1DFC7',
    borderColor: '#C9A989',
    borderRadius: 9,
    borderWidth: 1,
    color: colors.ink,
    fontSize: 14,
    fontWeight: '800',
    minHeight: 38,
    paddingHorizontal: 9,
    textAlign: 'center',
  },
  attendanceQuickButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 9,
    justifyContent: 'center',
    minHeight: 36,
    paddingHorizontal: 8,
  },
  attendanceQuickButtonDisabled: {
    backgroundColor: '#A78D7A',
  },
  attendanceQuickButtonText: {
    color: colors.onDark,
    fontSize: 11,
    fontWeight: '900',
  },
  attendanceTable: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  attendanceRow: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    minHeight: 44,
  },
  attendanceHeaderRow: {
    backgroundColor: colors.amberSoft,
  },
  attendanceSundayRow: {
    backgroundColor: '#F8ECE5',
  },
  attendanceCell: {
    color: colors.ink,
    flex: 1,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    paddingHorizontal: 6,
    textAlign: 'center',
  },
  attendanceDateCell: {
    flex: 0.7,
  },
  attendanceWeekdayCell: {
    flex: 0.9,
  },
  attendanceInput: {
    backgroundColor: '#F1DFC7',
    borderColor: '#C9A989',
    borderRadius: 10,
    borderWidth: 1,
    color: colors.ink,
    flex: 1,
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: 0,
    marginHorizontal: 5,
    minHeight: 42,
    minWidth: 0,
    paddingHorizontal: 7,
    paddingVertical: 0,
    textAlign: 'center',
  },
  attendanceInputReadonly: {
    backgroundColor: '#E6D9C8',
    borderColor: colors.line,
    color: colors.muted,
  },
  attendanceSundayInput: {
    backgroundColor: '#F0DCD5',
    borderColor: 'rgba(180, 72, 60, 0.25)',
    color: colors.rose,
  },
  payrollSummary: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
  },
  summaryLine: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    minHeight: 42,
    paddingHorizontal: 12,
  },
  summaryLineStrong: {
    backgroundColor: colors.gold,
  },
  summaryLineLabel: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  summaryLineLabelStrong: {
    color: colors.dark,
    fontWeight: '900',
  },
  summaryLineValue: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: 0,
  },
  summaryLineValueStrong: {
    color: colors.dark,
  },
  managerPanel: {
    gap: 12,
    marginTop: 8,
  },
  managerPayrollList: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 11,
    padding: 13,
  },
  managerPayrollListHeading: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  managerPayrollListTitleWrap: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 7,
  },
  managerPayrollListTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  managerPayrollRefresh: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderColor: colors.line,
    borderRadius: 9,
    borderWidth: 1,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  managerPayrollEmpty: {
    color: colors.muted,
    fontSize: 12,
    lineHeight: 18,
  },
  managerPayrollError: {
    color: colors.rose,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 18,
  },
  managerPayrollEmployeeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  managerPayrollEmployeeCard: {
    alignItems: 'center',
    borderRadius: 12,
    borderWidth: 1,
    justifyContent: 'center',
    minHeight: 58,
    minWidth: 0,
    paddingHorizontal: 11,
    paddingVertical: 9,
    textAlign: 'left',
    width: 'calc(50% - 4px)',
  },
  managerPayrollEmployeeCardPending: {
    backgroundColor: '#E6E3DF',
    borderColor: '#C9C3BC',
  },
  managerPayrollEmployeeCardApproved: {
    backgroundColor: colors.blue,
    borderColor: colors.blue,
  },
  managerPayrollEmployeeCardSelected: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  managerPayrollEmployeeName: {
    color: colors.ink,
    fontSize: 13,
    fontWeight: '900',
  },
  managerPayrollEmployeeNameApproved: {
    color: colors.onDark,
  },
  managerPayrollEmployeeNameSelected: {
    color: colors.onDark,
  },
  managerPayrollEmployeeMeta: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 2,
  },
  managerPayrollEmployeeMetaApproved: {
    color: 'rgba(255, 248, 238, 0.82)',
  },
  managerPayrollEmployeeMetaSelected: {
    color: 'rgba(255, 248, 238, 0.74)',
  },
  managerPayrollDetail: {
    backgroundColor: colors.surface,
    borderColor: colors.primarySoft,
    borderRadius: 17,
    borderWidth: 1,
    gap: 12,
    padding: 13,
  },
  managerPayrollDetailHeading: {
    alignItems: 'flex-start',
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'space-between',
  },
  managerPayrollDetailEyebrow: {
    color: colors.accent,
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 0.45,
  },
  managerPayrollDetailName: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '950',
    lineHeight: 23,
    marginTop: 2,
  },
  managerPayrollDetailHint: {
    color: colors.muted,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 3,
  },
  managerPayrollClose: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderRadius: 9,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  managerPayrollBackButton: {
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 12,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 6,
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  managerPayrollBackText: {
    color: colors.primary,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 16,
  },
  pendingText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    lineHeight: 18,
  },
  ownerBranchList: {
    gap: 8,
  },
  ownerBranchRow: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 10,
    minHeight: 68,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  ownerBranchRowActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  ownerBranchIcon: {
    alignItems: 'center',
    backgroundColor: colors.surfaceSoft,
    borderRadius: 8,
    height: 38,
    justifyContent: 'center',
    width: 38,
  },
  ownerBranchName: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  ownerBranchNameActive: {
    color: colors.onDark,
  },
  ownerBranchMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 3,
  },
  ownerBranchMetaActive: {
    color: colors.onDark,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: colors.primary,
    borderRadius: 999,
    flex: 1,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    minHeight: 50,
    paddingHorizontal: 14,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 18,
    elevation: 3,
  },
  dangerButton: {
    backgroundColor: colors.rose,
  },
  primaryButtonText: {
    color: colors.onDark,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
  },
  chipGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chipGroupCompact: {
    marginTop: -4,
  },
  chip: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 38,
    paddingHorizontal: 12,
    paddingVertical: 9,
  },
  chipCompact: {
    minHeight: 34,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  chipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  chipText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  chipTextActive: {
    color: colors.onDark,
  },
  supplySection: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    gap: 9,
    padding: 12,
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  supplySectionTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
  },
  supplyGrid: {
    display: 'grid',
    gap: 9,
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
  },
  supplyItemRow: {
    backgroundColor: colors.surface,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    gap: 9,
    padding: 10,
  },
  supplyItemHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  supplyItemName: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  supplyItemUnit: {
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 2,
  },
  supplyQuantityRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  supplyQuantityInput: {
    backgroundColor: colors.surfaceTint,
    borderColor: colors.lineStrong,
    borderRadius: 11,
    borderWidth: 1,
    color: colors.ink,
    flex: 1,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: 0,
    minHeight: 48,
    paddingHorizontal: 10,
    paddingVertical: 0,
  },
  supplyQuantityUnit: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
    minWidth: 48,
  },
  supplyStatusButton: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.lineStrong,
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 34,
    minWidth: 64,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  supplyStatusButtonEmpty: {
    backgroundColor: colors.roseSoft,
    borderColor: '#D79A91',
  },
  supplyStatusButtonText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  supplyStatusButtonTextEmpty: {
    color: colors.rose,
  },
  supplyStatusToggle: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 34,
    minWidth: 58,
    justifyContent: 'center',
    paddingHorizontal: 12,
  },
  supplyStatusToggleAvailable: {
    backgroundColor: colors.blue,
  },
  supplyStatusToggleEmpty: {
    backgroundColor: colors.rose,
  },
  supplyStatusToggleText: {
    color: colors.onDark,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  supplyStatusSwitch: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 3,
  },
  supplyStatusOption: {
    alignItems: 'center',
    borderRadius: 999,
    minHeight: 30,
    minWidth: 52,
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  supplyStatusOptionActive: {
    backgroundColor: colors.primary,
  },
  supplyStatusOptionEmpty: {
    backgroundColor: colors.rose,
  },
  supplyStatusOptionText: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0,
  },
  supplyStatusOptionTextActive: {
    color: colors.onDark,
  },
  supplyStatusOptionTextEmpty: {
    color: colors.onDark,
  },
  gridTwo: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  calculationBox: {
    alignItems: 'center',
    backgroundColor: colors.amberSoft,
    borderColor: '#E2B889',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  calculationLabel: {
    color: colors.amber,
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: 0,
  },
  calculationValue: {
    color: colors.ink,
    fontSize: 18,
    fontWeight: '900',
    letterSpacing: 0,
  },
  closeSummary: {
    alignItems: 'center',
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 14,
  },
  summaryDivider: {
    backgroundColor: colors.line,
    height: 42,
    width: 1,
  },
  summaryLabel: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '800',
    letterSpacing: 0,
    marginBottom: 4,
  },
  summaryValue: {
    color: colors.ink,
    fontSize: 17,
    fontWeight: '900',
    letterSpacing: 0,
  },
  history: {
    backgroundColor: colors.surfaceStrong,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    marginTop: 2,
    overflow: 'hidden',
    shadowColor: colors.deep,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.07,
    shadowRadius: 16,
    elevation: 2,
  },
  historyHeader: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    backgroundColor: colors.surface,
    flexDirection: 'row',
    gap: 8,
    padding: 13,
  },
  historyTitle: {
    color: colors.ink,
    fontSize: 15,
    fontWeight: '900',
    letterSpacing: 0,
  },
  historyRow: {
    alignItems: 'center',
    borderBottomColor: colors.line,
    borderBottomWidth: 1,
    flexDirection: 'row',
    gap: 10,
    padding: 13,
  },
  historyRowTitle: {
    color: colors.ink,
    fontSize: 14,
    fontWeight: '900',
    letterSpacing: 0,
  },
  historyRowMeta: {
    color: colors.muted,
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0,
    marginTop: 3,
  },
  historyRowValue: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    marginTop: 4,
  },
  emptyText: {
    color: colors.muted,
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0,
    padding: 14,
  },
});
