-- Phase 3 hardening: optimistic-concurrency metadata + audit log.
-- IMPORTANT:
--   1) Apply this migration to a staging/test Supabase project first.
--   2) This file is staged in Git by PR 20 but is NOT executed by the codemod.
--   3) Client-side compare-and-swap behavior is introduced only in later PRs.

begin;

alter table public.attendance_sheets
  add column if not exists version bigint not null default 1;

alter table public.branch_payroll_confirmations
  add column if not exists version bigint not null default 1;

create or replace function public.bump_operational_row_version()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.version := old.version + 1;
  new.updated_at := now();
  return new;
end;
$$;

drop trigger if exists attendance_sheets_bump_version on public.attendance_sheets;
create trigger attendance_sheets_bump_version
before update on public.attendance_sheets
for each row execute function public.bump_operational_row_version();

drop trigger if exists branch_payroll_confirmations_bump_version on public.branch_payroll_confirmations;
create trigger branch_payroll_confirmations_bump_version
before update on public.branch_payroll_confirmations
for each row execute function public.bump_operational_row_version();

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid,
  actor_role text,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  branch_id text,
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_entity_idx
  on public.audit_logs (entity_type, entity_id, created_at desc);

create index if not exists audit_logs_branch_idx
  on public.audit_logs (branch_id, created_at desc);

create index if not exists audit_logs_actor_idx
  on public.audit_logs (actor_id, created_at desc);

alter table public.audit_logs enable row level security;

drop policy if exists audit_logs_owner_read on public.audit_logs;
create policy audit_logs_owner_read
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'owner'
  )
);

drop policy if exists audit_logs_manager_branch_read on public.audit_logs;
create policy audit_logs_manager_branch_read
on public.audit_logs
for select
to authenticated
using (
  exists (
    select 1
    from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 'manager'
      and profiles.branch_id = audit_logs.branch_id
  )
);

create or replace function public.append_audit_log(
  p_action text,
  p_entity_type text,
  p_entity_id text,
  p_branch_id text,
  p_before_data jsonb default null,
  p_after_data jsonb default null
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_actor_id uuid := auth.uid();
  v_actor_role text;
  v_actor_branch text;
  v_id bigint;
begin
  if v_actor_id is null then
    raise exception 'Authentication required';
  end if;

  select role, branch_id
    into v_actor_role, v_actor_branch
  from public.profiles
  where id = v_actor_id;

  if v_actor_role is null then
    raise exception 'Profile not found';
  end if;

  if v_actor_role = 'employee' then
    raise exception 'Employees cannot write audit events directly';
  end if;

  if v_actor_role = 'manager'
     and (v_actor_branch is null or p_branch_id is distinct from v_actor_branch) then
    raise exception 'Managers can only audit their own branch';
  end if;

  insert into public.audit_logs (
    actor_id,
    actor_role,
    action,
    entity_type,
    entity_id,
    branch_id,
    before_data,
    after_data
  )
  values (
    v_actor_id,
    v_actor_role,
    p_action,
    p_entity_type,
    p_entity_id,
    p_branch_id,
    p_before_data,
    p_after_data
  )
  returning id into v_id;

  return v_id;
end;
$$;

revoke all on function public.append_audit_log(text, text, text, text, jsonb, jsonb) from public;
grant execute on function public.append_audit_log(text, text, text, text, jsonb, jsonb) to authenticated;

commit;
